name: Build Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Setup Environment Variables
      run: |
        echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> $GITHUB_ENV
        echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> $GITHUB_ENV

    - name: Run Tests
      run: npm run test

    - name: Clear dist directory
      run: rm -rf dist || true

    - name: Run Build
      run: npm run build

    - name: Upload Coverage Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/

    - name: Upload Build Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-report
        path: dist/

    - name: Notify on Failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Build Failed: ${new Date().toISOString()}`,
            body: 'Build or tests failed. Please check the workflow logs for details.'
          });

    - name: Cache Invalidation Check
      run: |
        echo "Checking for cached files..."
        find dist -type f -exec sha256sum {} \;